#!/usr/bin/env python3

# Problem 2: Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

def fibonacci():
    i, j = 1, 1
    while True:
        yield i
        i, j = j, i+j

def evens(g):
    for i in g:
        if i % 2 == 0:
            yield i

def lessthan4Ms(g):
    for i in g:
        if i >= 4000000:
            break
        yield i

def problem2():
    return sum(lessthan4Ms(evens(fibonacci())))

if __name__ == '__main__':
    print(problem2())
